# Generated by Django 4.2.1 on 2023-08-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("applied_in_companies", models.IntegerField(default=0)),
                ("rejected", models.IntegerField(default=0)),
                ("in_process", models.IntegerField(default=0)),
            ],
        ),
    ]
