# Generated by Django 4.2.1 on 2023-08-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo1_1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="id",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="shortlisted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
